version: '3'

services:
  news-feed-service-database:
    image: ghcr.io/helpet-app/news-feed-service-database:0.0.1-snapshot
    container_name: news-feed-service-database
    ports:
      - '5436:5432'
    env_file:
      - .news-feed-service-database.env
    volumes:
      - news-feed-service-database-data:/var/lib/postgresql/data/
  news-feed-service:
    image: ghcr.io/helpet-app/news-feed-service:0.0.1-snapshot
    container_name: news-feed-service
    env_file:
      - .news-feed-service.env
    depends_on:
      - news-feed-service-database
    networks:
      - helpet-network
    restart: always

volumes:
  news-feed-service-database-data:
    driver: local

networks:
  helpet-network:
    external: true